spring:
  config:
    import: C:\Users\Администратор\Desktop\Skillbox\data\hrskillninja\application-db.yaml
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

server:
  port: 8090
